### ISSUE TITLE
Add workflow utilities

### ISSUE THREAD

**Issue by tsurdilo** [serverlessworkflow/sdk-java#127]
**What would you like to be added**:
Add utility methods that implementors can use instead of having to write it themselves.
Ideas such as:
1. getStartingState
2. getStatesByType
3. getNextState
4. getConsumedEvents
5. getProducedEvents
6. getFunctionsDefsForAction
7. getActionsForFunctionDef
8. ...

**Comment by manick02** [comment]
I will look at this one and come back

**Comment by tsurdilo** [comment]
nice. thanks! idea is to create a top-level module like api/spi/validation etc and provide static util methods that take in a Workflow object as one of the params and return whatever is needed per util method.

**Comment by manick02** [comment]
Do we have to create utils ? I feel the code is lot structured if added as part of API (module). We have a lot of test workflows and utility test methods already in API which we can re-use for our unit tests for the above requirement.

**Comment by manick02** [comment]
@tsurdilo what does getNextState mean from runtime perspective? What is the functionality utility class should solve for here?

**Comment by tsurdilo** [comment]
@manick02 good point. yeah i think no need to add that one.

**Comment by manick02** [comment]
> @manick02 could we also add "getNumOfXYZ" methods, for example:
> 
> getNumOfStates() getNumOfStates(State.Type) getNumOfEndStates() getNumOfTransitions() getNumOfCompensationStates() getNumOfContinueAs() getNumOfActions() ... wdyt?
We can, Will runtime need these methods

**Comment by tsurdilo** [comment]
i think we can close this now. we can open new issues for specific util methods that we want to add
