### ISSUE TITLE
CallbackState validated incorrectly

### ISSUE THREAD

**Issue by jrpedrianes** [serverlessworkflow/sdk-java#187]
I think that the CallbackState validation is incorrect

https://github.com/serverlessworkflow/sdk-java/blob/a37b4642a0b2f9eb181eff3a368f92ecbe813ab7/validation/src/main/java/io/serverlessworkflow/validation/WorkflowValidatorImpl.java#L333

This line must be negated, isn't?

**Comment by tsurdilo** [comment]
fixed via https://github.com/serverlessworkflow/sdk-java/pull/188

**Comment by jrpedrianes** [comment]
Thanks @tsurdilo, do you plan to do a release including this fix soon?
