### ISSUE TITLE
Published version 4.0.3.Final does not contains the latest changes

### ISSUE THREAD

**Issue by jrpedrianes** [serverlessworkflow/sdk-java#192]
**What happened**:

The artifact published into maven central repository seems that is not compiled with the latest changes.

**How to reproduce it**:

Download the binary from:

- https://repo1.maven.org/maven2/io/serverlessworkflow/serverlessworkflow-validation/4.0.3.Final/serverlessworkflow-validation-4.0.3.Final.jar
- https://repo1.maven.org/maven2/io/serverlessworkflow/serverlessworkflow-validation/4.0.3.Final/serverlessworkflow-validation-4.0.3.Final-sources.jar

And review if the latest changes are applied. 

For example, If you go to `WorkflowValidatorImpl.java` file to line 333, the code must be the next:

```
                    if (!haveFunctionDefinition(
                        callbackState.getAction().getFunctionRef().getRefName(), functions)) {
                      addValidationError(
                          "CallbackState action function ref does not reference a defined workflow function definition",
                          ValidationError.WORKFLOW_VALIDATION);
                    }
```

But the code seems that is the old version.

**Environment**:
- Specification version used: serverlessworkflow-validation-4.0.3.Final

**Comment by jrpedrianes** [comment]
@tsurdilo could you look at this? 

sorry if you are not the guy that handles this, but I saw that you fixed a similar issue. https://github.com/serverlessworkflow/sdk-java/issues/187

**Comment by tsurdilo** [comment]
@jrpedrianes thanks for reporting this, will look into it asap. 

The change for validation is in 4.0.x branch, not sure how it did not end up in latest release, see https://github.com/serverlessworkflow/sdk-java/commit/cb618c1bd0a9d19fdf44fe4d734c6b59993b1310
and https://github.com/serverlessworkflow/sdk-java/blob/main/validation/src/main/java/io/serverlessworkflow/validation/WorkflowValidatorImpl.java#L333

Will look at the release jars and try to find out what happened. Thanks.

**Comment by tsurdilo** [comment]
@jrpedrianes idk what happened buy yes the source jars show the old version you are correct. How urgent is this for you. I could cut 4.0.4.Final release end of this week if thats ok

**Comment by jrpedrianes** [comment]
@tsurdilo, no problem, is not too urgent when you can fix it will be ok.

**Comment by jrpedrianes** [comment]
Any news about this?

**Comment by tsurdilo** [comment]
I haven't done the release yet, sorry. Will do this week.

**Comment by jrpedrianes** [comment]
any news on this? any plan to get a new release fixing this?

**Comment by ricardozanini** [comment]
Let me reopen this and close it once we release 4.0.4.

**Comment by jrpedrianes** [comment]
I checked right now and is fixed. 

Thanks
