### ISSUE TITLE
Dependency 'org.json' has vulnerabilities

### ISSUE THREAD

**Issue by jrpedrianes** [serverlessworkflow/sdk-java#193]
**What happened**:

Dependency `org.json` is a transitive dependency from  `everit-json-schema` that has vulnerabilities (CVE Name: Cx78f40514-81ff)

https://github.com/stleary/JSON-java/issues/484

The `everit-json-schema` maintainer released a new version fixing it: https://github.com/everit-org/json-schema/releases

**Comment by tsurdilo** [comment]
Thanks for reporting this. Will update and test.

**Comment by cb-manick** [comment]
I will take a look at this

**Comment by jrpedrianes** [comment]
Here you have a link where the issue is examined: https://github.com/stleary/JSON-java/issues/484, the first is not correct 🤷‍♂️, I'm going to change it.

Also indicate that commons-validator depends on commons-collections and in version 1.6 has a minor issue, see: 

https://issues.apache.org/jira/browse/COLLECTIONS-701
https://github.com/checkmarx-ts/checkmarx-github-action/issues/187

**Comment by jrpedrianes** [comment]
sorry :(, dirty hands 😮‍💨

**Comment by jrpedrianes** [comment]
I think that you can use this https://github.com/apps/whitesource-for-github-com for free in github public repositories

**Comment by tsurdilo** [comment]
Ok yeah let's give that try definitely, thanks.

**Comment by tsurdilo** [comment]
enabled for all sdk repos

**Comment by tsurdilo** [comment]
weird, whitesource is part of our build now but its not reporting this particular issue

**Comment by manick02** [comment]
@jrpedrianes  what tool identified this vulnerability? @tsurdilo how can I access vulnerability report for this repo

**Comment by tsurdilo** [comment]
@manick02 this was the last scan performed: https://github.com/serverlessworkflow/sdk-java/runs/6085322739
did not have any reported issues. 
Probably still best to upgrade https://github.com/serverlessworkflow/sdk-java/blob/main/pom.xml#L62
to latest version 1.14.1 as @jrpedrianes mentioned - https://mvnrepository.com/artifact/com.github.erosb/everit-json-schema

**Comment by jrpedrianes** [comment]
@manick02 I use a tool integrated into my IDE. 

I use IntelliJ IDEA 2022.1 (Ultimate Edition) which has a panel called "Dependency checker" that alerts me of all these vulnerabilities. For example in your case alerts me two:

- Cxdb5a1032-eda2
- Cx78f40514-81ff

<img width="471" alt="Captura de Pantalla 2022-04-20 a las 7 21 39" src="https://user-images.githubusercontent.com/1927286/164163482-206c3572-c936-484a-9858-166c9ca5a021.png">

**Comment by jrpedrianes** [comment]
Seems that my IDE is using [Checkmarx](https://checkmarx.com/) under the hood.

I don't know if this tool has a free plan, but seems that you can integrate it into Gitbub https://checkmarx.atlassian.net/wiki/spaces/SD/pages/2459697268/GitHub+Actions+Integration, or launch directly from maven https://checkmarx.atlassian.net/wiki/spaces/SD/pages/1339130085/Maven+Plugin

<img width="1741" alt="Captura de Pantalla 2022-04-20 a las 7 40 12" src="https://user-images.githubusercontent.com/1927286/164166258-e6fbba20-c259-455a-99aa-123ec9474bc2.png">

**Comment by jrpedrianes** [comment]
Also, Github has a tool named "Dependabot alerts", that scans the project dependencies, but I don't know if transitive ones are detected too. You can enable it in Settings -> Code security and analysis -> Dependabot alerts

**Comment by manick02** [comment]
Thanks @jrpedrianes I will check it out, and will try to setup some form of this tool

> @manick02 I use a tool integrated into my IDE.
> 
> I use IntelliJ IDEA 2022.1 (Ultimate Edition) which has a panel called "Dependency checker" that alerts me of all these vulnerabilities. For example in your case alerts me two:
> 
> * Cxdb5a1032-eda2
> * Cx78f40514-81ff
> 
> <img alt="Captura de Pantalla 2022-04-20 a las 7 21 39" width="471" src="https://user-images.githubusercontent.com/1927286/164163482-206c3572-c936-484a-9858-166c9ca5a021.png">

**Comment by jrpedrianes** [comment]
Any news about this?

**Comment by tsurdilo** [comment]
@manick02 ^^

**Comment by manick02** [comment]
@tsurdilo fix for json schema vulnerability is already approved by you and its in master branch already

**Comment by tsurdilo** [comment]
oops sorry checking
