### ISSUE TITLE
Mis-match between spec and implementation for switch state condition

### ISSUE THREAD

**Issue by ADeane6** [serverlessworkflow/sdk-java#200]
**What happened**:
Currently, the SDK model defines data conditions of switch states as requiring a transition, this doesn't match the spec as it's outlined that **either** end or transition can be specified
Spec: https://github.com/serverlessworkflow/specification/blob/0.8.x/specification.md#switch-state-data-conditions

Implementation: https://github.com/serverlessworkflow/sdk-java/blob/cefa865372f31d0c65ae8213e3a4a95c30c92e98/api/src/main/resources/schema/switchconditions/datacondition.json#L26-L29

**What you expected to happen**:
SDK adheres to spec as defined
https://github.com/serverlessworkflow/specification/blob/0.8.x/specification.md#switch-state-data-conditions

**Environment**:
- Specification version used: 0.8

**Comment by tsurdilo** [comment]
@ADeane6 thanks for reporting, will take a look asap

**Comment by tsurdilo** [comment]
pr: https://github.com/serverlessworkflow/sdk-java/pull/201
