### ISSUE TITLE
POJOs being generated with initialized collections by default

### ISSUE THREAD

**Issue by hbelmiro** [serverlessworkflow/sdk-java#204]
POJOs are being generated with initialized collections by default. This causes properties not set in the workflow to be unmarshaled to empty collections.

For instance, given the following JSON:

```json
{
  "id": "helloworld",
  "annotations": ["hello", "world"]
}
```

`getAnnotations()` should return a collection with two objects. This is working as expected.

Given the followin JSON:

```json
{
  "id": "helloworld",
  "annotations": []
}
```

`getAnnotations()` should return an empty collection. This is also working as expected.

Given the followin JSON: 

```json
{
  "id": "helloworld"
}
```

`getAnnotations()` should return `null`, but currently it's returning an empty collection. Here's the problem.

This is a problem because there are properties that aren't required, but when present, they should not be empty.
Translating this to Java:
| Value | Valid |
| --------| ------- |
| `null` | Yes |
| empty | No |
| not empty | Yes |

To fix this behavior, we just need to set [initializeCollections](https://joelittlejohn.github.io/jsonschema2pojo/site/1.1.2/generate-mojo.html#initializeCollections) to `false` in [pom.xml](https://github.com/serverlessworkflow/sdk-java/blob/8a61e3cb23f6ae75d2d711410bff974322717d77/api/pom.xml#L94).

**But, this change can break compatibility, since methods that today never return `null` might return `null` after the change, which may cause `NullPointerExceptions` to users.**

So, what do you guys think? Can I submit a PR to fix this issue?

**Comment by tsurdilo** [comment]
i think this was fixed via https://github.com/serverlessworkflow/sdk-java/commit/8a61e3cb23f6ae75d2d711410bff974322717d77

**Comment by hbelmiro** [comment]
It wasn't.
We can confirm that in [this assertion](https://github.com/serverlessworkflow/sdk-java/blob/8a61e3cb23f6ae75d2d711410bff974322717d77/api/src/test/java/io/serverlessworkflow/api/test/MarkupToWorkflowTest.java#L232). It should be failing, since `produceEvents` is not defined in the workflow.

```java
assertNotNull(defaultDefinition.getTransition().getProduceEvents());
```

```json
      "defaultCondition": {
        "transition": {
          "nextState": "RejectApplication",
          "compensate": true
        }
      }
```

**Comment by tsurdilo** [comment]
| getAnnotations() should return null, but currently it's returning an empty collection

I think this is looking from the point of runtimes, not end users. So far I have kinda done this on purpose to only print values back as json from object model that actually have values. Is it problem to check for null and empty in this case?

**Comment by hbelmiro** [comment]
> ok is it bad to check for null + empty in this case? I am kinda not following the issue sorry :(

It is, because there are cases that null is a valid value, but empty isn't. [Annotations](https://github.com/serverlessworkflow/specification/blob/main/specification.md#workflow-definition-structure) is one of them. For these cases, a valid workflow will result in an invalid instance of `Workflow`.

**Comment by tsurdilo** [comment]
hmmm can u explain ? null is never a valid value for json yaml. if its empty or not in markup should be same thing??

**Comment by hbelmiro** [comment]
Sorry. By null I meant absent.
For instance, as `annotations` is not required, the following is a valid workflow:
```json
{
  "id": "absent"
}
```
The following is also valid:
```json
{
  "id": "ab",
  "annotations": [ "a", "b" ]
}
```
But, the following is invalid, since `annotations` minSize = 1:
```json
{
  "id": "empty",
  "annotations": [ ]
}
```

So, a valid workflow like the above with id = "absent" will be parsed to an invalid instance of `Workflow` (it is an invalid instance because getAnnotations.size() == 0)

**Comment by tsurdilo** [comment]
thanks! yeah in tests we rly need to add validation (json schema) of generated outputs. this is rly important
