### ISSUE TITLE
Started SDK for java

### ISSUE THREAD

**Issue by davideduma** [serverlessworkflow/sdk-java#214]
i am trying compile SDK java but i was getting error because IDE not found JAR.
For example:

import io.serverlessworkflow.api.Workflow;
import io.serverlessworkflow.api.actions.Action;
import io.serverlessworkflow.api.auth.AuthDefinition;
import io.serverlessworkflow.api.branches.Branch;

this jar not exists in the dependency maven.

![image](https://user-images.githubusercontent.com/86481341/204016930-75d5ec9d-b53f-46a5-b455-1cfb6acdfef2.png)

I want to become contributor but i not know how compile SDK and use.
the readme document is not enough. something is missing

Thanks

**Comment by hbelmiro** [comment]
@davideduma what happens when you run `mvn clean verify -DskipTests`?
Can you provide a reproducer?

**Comment by davideduma** [comment]
@hbelmiro. it's working right now. i've configured java_home with version 8 so this is my error. now it is working very well with 11 version java. Thanks!
