### ISSUE TITLE
Version 5.0.0-SNAPSHOT release notes

### ISSUE THREAD

**Issue by visheshruparelia** [serverlessworkflow/sdk-java#222]
Hi, I was trying to upgrade the SDK's dependency from `4.0.3-FINAL` to `5.0.0-SNAPSHOT` but before I do that, I wanted to know if are there any breaking changes etc. I tried searching for the release notes but could not find it. Can someone help?

**Comment by visheshruparelia** [comment]
Also, is `5.0.0-FINAL` available?

**Comment by ricardozanini** [comment]
@visheshruparelia I'm terribly sorry for the late reply, I'm just catching up here and trying to put everything on track. 

5.0.0 will be released with 0.9 spec version. I'm preparing a 4.0.5 that contains your fix plus a bunch of CVE fixes. You can try the PR on your end if you don't mind. #273
