### ISSUE TITLE
Jakarta update

### ISSUE THREAD

**Issue by radtriste** [serverlessworkflow/sdk-java#225]
Spring Boot 3 is out and Quarkus 3 should be really soon and both frameworks migrated to jakarta libraries.

Would it be possible to update the codebase to use jakarta in the next version ?
Or try to maintain 2 versions: one with javax and one with jakarta ?

The problem is mainly with the `validation-api` library dependency

**Comment by radtriste** [comment]
I can provide a PR for the jakarta update if needed

**Comment by radtriste** [comment]
btw, not sure it is used at all into the project: https://github.com/serverlessworkflow/sdk-java/search?q=javax

**Comment by ricardozanini** [comment]
I think we can release a 4.1.0 version following 4.0.5 with Java 11 and Jakarta support.
