### ISSUE TITLE
grantType "resourceOwner" mentioned in 0.8 but not supported in sdk 4.0.5-FINAL

### ISSUE THREAD

**Issue by mahith2108** [serverlessworkflow/sdk-java#369]
**What happened**: grantType "resourceOwner" mentioned in 0.8 but not supported in sdk

**What you expected to happen**: resourceOwner support should be present

**How to reproduce it**:  Add grantType as "resourceOwner"

**Anything else we need to know?**:

**Environment**:
- Specification version used:
- 4.0.5-FINAL java sdk  spec 0.8
Need the fix to be available 4.0.x as we are using 0.8
ref: https://github.com/serverlessworkflow/sdk-java/issues/364

**Comment by ricardozanini** [comment]
Closing since it's a duplication of #364
