### ISSUE TITLE
Where to find 7.0.0.Final build

### ISSUE THREAD

**Issue by sandeep-paliwal** [serverlessworkflow/sdk-java#389]
**Where to find 7.0.0.Final build**:
Hi, 
Maven repository only shows [5.0.0.Final build](https://mvnrepository.com/artifact/io.serverlessworkflow/serverlessworkflow-api )
But the Readme documentation mentions 7.0.0.Final. 
Where can we use that build from?

**Comment by ricardozanini** [comment]
Hi @sandeep-paliwal, we haven't released the 7.0.0 version yet. You can build from `main` to have a snapshot.

**Comment by ricardozanini** [comment]
Hi! follow this PR to have the updates about the release version: #404

**Comment by ricardozanini** [comment]
@sandeep-paliwal you can get the `7.0.0-alpha1` version here: https://central.sonatype.com/artifact/io.serverlessworkflow/serverlessworkflow-api

Please follow the project to get notified when we release new versions! 👍
