### ISSUE TITLE
[BUG][7.0.0] Error when parsing listen task (one,all,any)

### ISSUE THREAD

**Issue by uasouz** [serverlessworkflow/sdk-java#412]
**What happened**:

During a debug session on a runtime implementation in Java one of our new tests failed due to error when reading and parsing the workflow YAML file.
After some time we found suppresed errors showing that the expected fields inside the `to` block of `listen` was expecting diferent keys than the ones specified on the spec.

![Captura de tela de 2024-08-21 11-09-17](https://github.com/user-attachments/assets/5767fe78-364e-442a-8383-8a849daff0c4)

I also replicated the failure with tests on the SDK project by adding a new test.

![Captura de tela de 2024-08-21 11-22-02](https://github.com/user-attachments/assets/522b7cbe-fe67-49a2-9cdd-f913a832ac68)

**What you expected to happen**:

For the YAML to be parsed correctly and expect the format complying with the SW specification.

**How to reproduce it**:
Add a `listen` task to any workflow using `with.to.any` or `with.to.one` or `with.to.all`

**Anything else we need to know?**:

**Environment**:
- Specification version used: 1.0.0-alpha2

**Comment by fjtirado** [comment]
@uasouz For further issues, it would be far easier to debug, rather than attaching images, a string with the content of the workflow being tested and the stack trace.

**Comment by uasouz** [comment]
> @uasouz For further issues, it would be far easier to debug, rather than attaching images, a string with the content of the workflow being tested and the stack trace. 

Thanks for the feedback, next time I will add more text and the stack trace.
