### ISSUE TITLE
Parameters or Arguments

### ISSUE THREAD

**Issue by mcruzdev** [serverlessworkflow/sdk-java#493]
**What is the question**:
Looking the [specification](https://github.com/serverlessworkflow/specification/blob/main/dsl-reference.md#openapi-call), we can see the property  `arguments`, but looking the `WithOpenAPIParameters` class we can see `parameters`. What is the right one `parameters` or `arguments`?

**Comment by fjtirado** [comment]
@mcruzdev There is a discrepancy between spec document you linked and spec [schema](https://github.com/serverlessworkflow/specification/blob/main/schema/workflow.yaml#L392)
In those cases, we should go with schema and open an issue in the spec to fix the discrepancy.
