### ISSUE TITLE
Enhancements to the SVG diagram generation for a workflow.

### ISSUE THREAD

**Issue by mohnishkodnani** [serverlessworkflow/sdk-java#53]
**What would you like to be added**:
For States which have actions associated in an array, a way to look at the actions in detail or atleast the names of the actions. 
Right now, the diagram is linear. For ex: If there is a Parallel State, with 3 flows , the SVG generated just has a box, that says number of actions = 3.Similarly for Event state, if there are actions it just lists the number of actions.

May be a collapsible box, which when clicked shows more details. 

**Why is this needed**:
One of the reasons to have an SVG, is to make it easier to understand the steps in the logic. It would be nice if we can dig into details on the diagram itself rather than going into the JSON to figure out what detailed actions,  are associated with a State. 

I talked about this on the slack channel. The link to the conversation is [here](https://cloud-native.slack.com/archives/CMBAZQSEP/p1614046903011000). 

@tsurdilo created a gist for it [here](https://gist.github.com/tsurdilo/ab65d49e3c6a9e679c6f2501bbdf635f).
I would enhance that with a Merge step as well, which show cases that with the default strategy of "and" as completion, the workflow will wait for all to finish and merge the results from each of the flows before passing them as data to the subsequent downstream tasks.

**Comment by tsurdilo** [comment]
@mohnishkodnani thanks, will work on it as soon as possible
