### ISSUE TITLE
Whether to allow spaces in the state name

### ISSUE THREAD

**Issue by xinydev** [serverlessworkflow/sdk-java#71]
**What is the question**:   

online editor:https://serverlessworkflow.io/editor.html  ,the state name cannot have spaces.    

But in the examples,https://github.com/serverlessworkflow/specification/tree/main/examples#hello-world-example, there are spaces in state name

**Comment by tsurdilo** [comment]
@xinydev i think this is a current limitation of the diagram generation. The SW DSL allows spaces in state names. 
I will try to fix this asap
