### ISSUE TITLE
Wrong ISO8601 durations

### ISSUE THREAD

**Issue by Neuroglia** [serverlessworkflow/sdk-java#75]
**What happened**:

@tsurdilo Following [our discussion on the spec repo](https://github.com/serverlessworkflow/specification/issues/324), it configured my unit tests to run the [examples](https://github.com/serverlessworkflow/sdk-java/tree/main/api/src/test/resources/examples).

My tests fail with the booklending.json file, because an ISO 8601 duration is I believe in an invalid format: **PT2W** instead of **P2W**. Am I correct to assume it is a typo?

**What you expected to happen**:

When ISO 8601 values specify a period of time, they should be prefixed with 'P' instead of 'PT'

**How to reproduce it**:

Read the 'timeDelay' property with an ISO 8601 duration parser.

**Comment by tsurdilo** [comment]
@Neuroglia yeah its a typo, sorry. Will fix asap
