### ISSUE TITLE
Retry does not have increment that is defined in 0.6 version of the spec

### ISSUE THREAD

**Issue by mswiderski** [serverlessworkflow/sdk-java#77]
**What happened**:
Spec version 0.6 defines that retries have increment - a static value appended to each retry attempt but it does not existing is Java SDK. Most likely caused by not having it defined in the def json file  https://github.com/serverlessworkflow/sdk-java/blob/main/api/src/main/resources/schema/retry/retrydef.json

**What you expected to happen**:
Increment should be part of retry definition of Java SDK 
**How to reproduce it**:
just use Java SDK and look at the retry definition

**Comment by tsurdilo** [comment]
It was missing maxDelay as well. Will fix both
