### ISSUE TITLE
Add more options to diagram generation

### ISSUE THREAD

**Issue by tsurdilo** [serverlessworkflow/sdk-java#82]
**What would you like to be added**:
Add more options to diagram generation. Some ideas include
1) add option to display diagram vertically/horizontally
2) add option to define the min/max size of the generated diagram
3) add ability to display actions (service invocations)
4) add custom node representations for different states
**Why is this needed**:
to improve diagram generation

**Comment by manick02** [comment]
@tsurdilo Is this issue still relevant for me to pick it up?
